Add Unit
delowardev/vue3-circle-progress pull request #8
Opened 2022-05-17 06:22 UTC by Odumz

This PR seeks to add the ability to input a unit such as '%' in the circle progress

2022-05-23 07:21 UTC, delowardev requested changes

2022-05-23 07:21 UTC, delowardev commented on package.json
> +  },
Hi @Odumz, Thanks for your contribution. Can we not touch `package.json` & `package-lock.json` changes & push them? We don't want the `vue` as a dependency for now.

2022-05-23 13:20 UTC, Odumz commented on package.json
> +  },
Okay, I'll do that now

2022-05-24 10:13 UTC, merged

2022-05-24 10:15 UTC, delowardev commented
Thanks for your contribution, I will publish a new version to the npm soon.